<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />




<title>Results and Conclusion</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>


</head>

<body>

<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 51px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 56px;
  margin-top: -56px;
}

.section h2 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h3 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h4 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h5 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h6 {
  padding-top: 56px;
  margin-top: -56px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>


<div class="container-fluid main-container">

<!-- tabsets -->
<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});
</script>

<!-- code folding -->






<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Consciousness in Sleep</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Introduction</a>
</li>
<li>
  <a href="data.html">Data and Analysis</a>
</li>
<li>
  <a href="results.html">Results and Conclusion</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">



<h1 class="title toc-ignore">Results and Conclusion</h1>

</div>


<div id="time-to-fall-asleep-predicted-by-sfg-area" class="section level4">
<h4>Time to fall asleep predicted by SFG area</h4>
<pre class="r"><code>#Linear relationship between time to fall asleep and SFG area
summary(lm(PSQI_Min2Asleep[PSQI_Min2Asleep &lt;= 81] ~ FS_L_Superiorfrontal_Area[PSQI_Min2Asleep &lt;= 81] + Gender[PSQI_Min2Asleep &lt;= 81]))</code></pre>
<pre><code>## 
## Call:
## lm(formula = PSQI_Min2Asleep[PSQI_Min2Asleep &lt;= 81] ~ FS_L_Superiorfrontal_Area[PSQI_Min2Asleep &lt;= 
##     81] + Gender[PSQI_Min2Asleep &lt;= 81])
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -20.010 -10.043  -3.737   9.969  55.823 
## 
## Coefficients:
##                                                    Estimate Std. Error
## (Intercept)                                      29.3267495  3.8447336
## FS_L_Superiorfrontal_Area[PSQI_Min2Asleep &lt;= 81] -0.0014867  0.0005484
## Gender[PSQI_Min2Asleep &lt;= 81]M                    0.3132999  0.9995793
##                                                  t value Pr(&gt;|t|)    
## (Intercept)                                        7.628 5.18e-14 ***
## FS_L_Superiorfrontal_Area[PSQI_Min2Asleep &lt;= 81]  -2.711  0.00681 ** 
## Gender[PSQI_Min2Asleep &lt;= 81]M                     0.313  0.75401    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 14.02 on 1093 degrees of freedom
##   (90 observations deleted due to missingness)
## Multiple R-squared:  0.008222,   Adjusted R-squared:  0.006408 
## F-statistic: 4.531 on 2 and 1093 DF,  p-value: 0.01098</code></pre>
<pre class="r"><code>summary(lm(PSQI_Min2Asleep[PSQI_Min2Asleep &lt;= 81] ~ FS_R_Superiorfrontal_Area[PSQI_Min2Asleep &lt;= 81] + Gender[PSQI_Min2Asleep &lt;= 81]))</code></pre>
<pre><code>## 
## Call:
## lm(formula = PSQI_Min2Asleep[PSQI_Min2Asleep &lt;= 81] ~ FS_R_Superiorfrontal_Area[PSQI_Min2Asleep &lt;= 
##     81] + Gender[PSQI_Min2Asleep &lt;= 81])
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -20.246 -10.106  -3.607  10.008  55.836 
## 
## Coefficients:
##                                                    Estimate Std. Error
## (Intercept)                                      29.3281769  3.8120112
## FS_R_Superiorfrontal_Area[PSQI_Min2Asleep &lt;= 81] -0.0015217  0.0005563
## Gender[PSQI_Min2Asleep &lt;= 81]M                    0.3448223  1.0031697
##                                                  t value Pr(&gt;|t|)    
## (Intercept)                                        7.694 3.18e-14 ***
## FS_R_Superiorfrontal_Area[PSQI_Min2Asleep &lt;= 81]  -2.735  0.00633 ** 
## Gender[PSQI_Min2Asleep &lt;= 81]M                     0.344  0.73111    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 14.02 on 1093 degrees of freedom
##   (90 observations deleted due to missingness)
## Multiple R-squared:  0.008341,   Adjusted R-squared:  0.006526 
## F-statistic: 4.597 on 2 and 1093 DF,  p-value: 0.01028</code></pre>
<pre class="r"><code>#Linear relationship between time to fall asleep and SFG area + WBV
summary(lm(PSQI_Min2Asleep[PSQI_Min2Asleep &lt;= 81] ~ FS_L_Superiorfrontal_Area[PSQI_Min2Asleep &lt;= 81] + FS_BrainSeg_Vol[PSQI_Min2Asleep &lt;= 81] + Gender[PSQI_Min2Asleep &lt;= 81]))</code></pre>
<pre><code>## 
## Call:
## lm(formula = PSQI_Min2Asleep[PSQI_Min2Asleep &lt;= 81] ~ FS_L_Superiorfrontal_Area[PSQI_Min2Asleep &lt;= 
##     81] + FS_BrainSeg_Vol[PSQI_Min2Asleep &lt;= 81] + Gender[PSQI_Min2Asleep &lt;= 
##     81])
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -20.198 -10.089  -3.585   9.954  55.942 
## 
## Coefficients:
##                                                    Estimate Std. Error
## (Intercept)                                       3.250e+01  5.013e+00
## FS_L_Superiorfrontal_Area[PSQI_Min2Asleep &lt;= 81] -8.872e-04  8.186e-04
## FS_BrainSeg_Vol[PSQI_Min2Asleep &lt;= 81]           -6.625e-06  6.717e-06
## Gender[PSQI_Min2Asleep &lt;= 81]M                    8.065e-01  1.118e+00
##                                                  t value Pr(&gt;|t|)    
## (Intercept)                                        6.483 1.36e-10 ***
## FS_L_Superiorfrontal_Area[PSQI_Min2Asleep &lt;= 81]  -1.084    0.279    
## FS_BrainSeg_Vol[PSQI_Min2Asleep &lt;= 81]            -0.986    0.324    
## Gender[PSQI_Min2Asleep &lt;= 81]M                     0.722    0.471    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 14.02 on 1092 degrees of freedom
##   (90 observations deleted due to missingness)
## Multiple R-squared:  0.009105,   Adjusted R-squared:  0.006383 
## F-statistic: 3.345 on 3 and 1092 DF,  p-value: 0.01863</code></pre>
<pre class="r"><code>summary(lm(PSQI_Min2Asleep[PSQI_Min2Asleep &lt;= 81] ~ FS_R_Superiorfrontal_Area[PSQI_Min2Asleep &lt;= 81] + FS_BrainSeg_Vol[PSQI_Min2Asleep &lt;= 81] + Gender[PSQI_Min2Asleep &lt;= 81]))</code></pre>
<pre><code>## 
## Call:
## lm(formula = PSQI_Min2Asleep[PSQI_Min2Asleep &lt;= 81] ~ FS_R_Superiorfrontal_Area[PSQI_Min2Asleep &lt;= 
##     81] + FS_BrainSeg_Vol[PSQI_Min2Asleep &lt;= 81] + Gender[PSQI_Min2Asleep &lt;= 
##     81])
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -20.393 -10.041  -3.551   9.904  55.576 
## 
## Coefficients:
##                                                    Estimate Std. Error
## (Intercept)                                       3.248e+01  5.012e+00
## FS_R_Superiorfrontal_Area[PSQI_Min2Asleep &lt;= 81] -9.307e-04  8.259e-04
## FS_BrainSeg_Vol[PSQI_Min2Asleep &lt;= 81]           -6.467e-06  6.679e-06
## Gender[PSQI_Min2Asleep &lt;= 81]M                    8.215e-01  1.117e+00
##                                                  t value Pr(&gt;|t|)    
## (Intercept)                                        6.480 1.38e-10 ***
## FS_R_Superiorfrontal_Area[PSQI_Min2Asleep &lt;= 81]  -1.127    0.260    
## FS_BrainSeg_Vol[PSQI_Min2Asleep &lt;= 81]            -0.968    0.333    
## Gender[PSQI_Min2Asleep &lt;= 81]M                     0.735    0.462    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 14.02 on 1092 degrees of freedom
##   (90 observations deleted due to missingness)
## Multiple R-squared:  0.009192,   Adjusted R-squared:  0.00647 
## F-statistic: 3.377 on 3 and 1092 DF,  p-value: 0.01783</code></pre>
<pre class="r"><code>#Linear relationship between time to fall asleep and WBV
summary(lm(PSQI_Min2Asleep[PSQI_Min2Asleep &lt;= 81] ~ FS_BrainSeg_Vol[PSQI_Min2Asleep &lt;= 81] + Gender[PSQI_Min2Asleep &lt;= 81]))</code></pre>
<pre><code>## 
## Call:
## lm(formula = PSQI_Min2Asleep[PSQI_Min2Asleep &lt;= 81] ~ FS_BrainSeg_Vol[PSQI_Min2Asleep &lt;= 
##     81] + Gender[PSQI_Min2Asleep &lt;= 81])
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -20.286  -9.857  -3.536  10.108  56.081 
## 
## Coefficients:
##                                          Estimate Std. Error t value
## (Intercept)                             3.233e+01  5.011e+00   6.452
## FS_BrainSeg_Vol[PSQI_Min2Asleep &lt;= 81] -1.203e-05  4.500e-06  -2.673
## Gender[PSQI_Min2Asleep &lt;= 81]M          8.272e-01  1.118e+00   0.740
##                                        Pr(&gt;|t|)    
## (Intercept)                            1.66e-10 ***
## FS_BrainSeg_Vol[PSQI_Min2Asleep &lt;= 81]  0.00762 ** 
## Gender[PSQI_Min2Asleep &lt;= 81]M          0.45938    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 14.02 on 1093 degrees of freedom
##   (90 observations deleted due to missingness)
## Multiple R-squared:  0.008039,   Adjusted R-squared:  0.006224 
## F-statistic: 4.429 on 2 and 1093 DF,  p-value: 0.01214</code></pre>
</div>
<div id="bad-dreams-predicted-by-hippocampus-volume" class="section level4">
<h4>Bad dreams predicted by hippocampus volume</h4>
<pre class="r"><code>#Linear relationship between bad dreams and hippo volume
summary(lm(PSQI_BadDream[PSQI_BadDream &lt;= 2.6] ~ FS_L_Hippo_Vol[PSQI_BadDream &lt;= 2.6] + Gender[PSQI_BadDream &lt;= 2.6]))</code></pre>
<pre><code>## 
## Call:
## lm(formula = PSQI_BadDream[PSQI_BadDream &lt;= 2.6] ~ FS_L_Hippo_Vol[PSQI_BadDream &lt;= 
##     2.6] + Gender[PSQI_BadDream &lt;= 2.6])
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -0.3988 -0.3396 -0.3007  0.6410  1.7373 
## 
## Coefficients:
##                                        Estimate Std. Error t value
## (Intercept)                           1.681e-01  1.618e-01   1.039
## FS_L_Hippo_Vol[PSQI_BadDream &lt;= 2.6]  4.231e-05  3.797e-05   1.114
## Gender[PSQI_BadDream &lt;= 2.6]M        -7.131e-02  3.712e-02  -1.921
##                                      Pr(&gt;|t|)  
## (Intercept)                             0.299  
## FS_L_Hippo_Vol[PSQI_BadDream &lt;= 2.6]    0.265  
## Gender[PSQI_BadDream &lt;= 2.6]M           0.055 .
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.5462 on 1097 degrees of freedom
##   (90 observations deleted due to missingness)
## Multiple R-squared:  0.003419,   Adjusted R-squared:  0.001602 
## F-statistic: 1.882 on 2 and 1097 DF,  p-value: 0.1528</code></pre>
<pre class="r"><code>summary(lm(PSQI_BadDream[PSQI_BadDream &lt;= 2.6] ~ FS_R_Hippo_Vol[PSQI_BadDream &lt;= 2.6] + Gender[PSQI_BadDream &lt;= 2.6]))</code></pre>
<pre><code>## 
## Call:
## lm(formula = PSQI_BadDream[PSQI_BadDream &lt;= 2.6] ~ FS_R_Hippo_Vol[PSQI_BadDream &lt;= 
##     2.6] + Gender[PSQI_BadDream &lt;= 2.6])
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -0.3779 -0.3415 -0.2985  0.6434  1.7290 
## 
## Coefficients:
##                                        Estimate Std. Error t value
## (Intercept)                           2.234e-01  1.784e-01   1.252
## FS_R_Hippo_Vol[PSQI_BadDream &lt;= 2.6]  2.882e-05  4.135e-05   0.697
## Gender[PSQI_BadDream &lt;= 2.6]M        -6.575e-02  3.815e-02  -1.724
##                                      Pr(&gt;|t|)  
## (Intercept)                            0.2108  
## FS_R_Hippo_Vol[PSQI_BadDream &lt;= 2.6]   0.4860  
## Gender[PSQI_BadDream &lt;= 2.6]M          0.0851 .
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.5464 on 1097 degrees of freedom
##   (90 observations deleted due to missingness)
## Multiple R-squared:  0.002732,   Adjusted R-squared:  0.0009142 
## F-statistic: 1.503 on 2 and 1097 DF,  p-value: 0.223</code></pre>
<pre class="r"><code>#Linear relationship between bad dreams and hippo volume + WBV
summary(lm(PSQI_BadDream[PSQI_BadDream &lt;= 2.6] ~ FS_L_Hippo_Vol[PSQI_BadDream &lt;= 2.6] + FS_BrainSeg_Vol[PSQI_BadDream &lt;= 2.6] + Gender[PSQI_BadDream &lt;= 2.6]))</code></pre>
<pre><code>## 
## Call:
## lm(formula = PSQI_BadDream[PSQI_BadDream &lt;= 2.6] ~ FS_L_Hippo_Vol[PSQI_BadDream &lt;= 
##     2.6] + FS_BrainSeg_Vol[PSQI_BadDream &lt;= 2.6] + Gender[PSQI_BadDream &lt;= 
##     2.6])
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -0.4005 -0.3397 -0.3007  0.6410  1.7358 
## 
## Coefficients:
##                                         Estimate Std. Error t value
## (Intercept)                            1.732e-01  2.069e-01   0.837
## FS_L_Hippo_Vol[PSQI_BadDream &lt;= 2.6]   4.325e-05  4.477e-05   0.966
## FS_BrainSeg_Vol[PSQI_BadDream &lt;= 2.6] -8.177e-09  2.067e-07  -0.040
## Gender[PSQI_BadDream &lt;= 2.6]M         -7.041e-02  4.358e-02  -1.616
##                                       Pr(&gt;|t|)
## (Intercept)                              0.403
## FS_L_Hippo_Vol[PSQI_BadDream &lt;= 2.6]     0.334
## FS_BrainSeg_Vol[PSQI_BadDream &lt;= 2.6]    0.968
## Gender[PSQI_BadDream &lt;= 2.6]M            0.106
## 
## Residual standard error: 0.5465 on 1096 degrees of freedom
##   (90 observations deleted due to missingness)
## Multiple R-squared:  0.00342,    Adjusted R-squared:  0.0006923 
## F-statistic: 1.254 on 3 and 1096 DF,  p-value: 0.289</code></pre>
<pre class="r"><code>summary(lm(PSQI_BadDream[PSQI_BadDream &lt;= 2.6] ~ FS_R_Hippo_Vol[PSQI_BadDream &lt;= 2.6] + FS_BrainSeg_Vol[PSQI_BadDream &lt;= 2.6] + Gender[PSQI_BadDream &lt;= 2.6]))</code></pre>
<pre><code>## 
## Call:
## lm(formula = PSQI_BadDream[PSQI_BadDream &lt;= 2.6] ~ FS_R_Hippo_Vol[PSQI_BadDream &lt;= 
##     2.6] + FS_BrainSeg_Vol[PSQI_BadDream &lt;= 2.6] + Gender[PSQI_BadDream &lt;= 
##     2.6])
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -0.3770 -0.3415 -0.2988  0.6435  1.7362 
## 
## Coefficients:
##                                         Estimate Std. Error t value
## (Intercept)                            2.011e-01  2.118e-01   0.950
## FS_R_Hippo_Vol[PSQI_BadDream &lt;= 2.6]   2.327e-05  5.019e-05   0.464
## FS_BrainSeg_Vol[PSQI_BadDream &lt;= 2.6]  4.156e-08  2.129e-07   0.195
## Gender[PSQI_BadDream &lt;= 2.6]M         -6.990e-02  4.368e-02  -1.600
##                                       Pr(&gt;|t|)
## (Intercept)                              0.343
## FS_R_Hippo_Vol[PSQI_BadDream &lt;= 2.6]     0.643
## FS_BrainSeg_Vol[PSQI_BadDream &lt;= 2.6]    0.845
## Gender[PSQI_BadDream &lt;= 2.6]M            0.110
## 
## Residual standard error: 0.5467 on 1096 degrees of freedom
##   (90 observations deleted due to missingness)
## Multiple R-squared:  0.002767,   Adjusted R-squared:  3.742e-05 
## F-statistic: 1.014 on 3 and 1096 DF,  p-value: 0.3858</code></pre>
</div>
<div id="results" class="section level2">
<h2>Results</h2>
<p>Initial analysis revealed a strong linear relationship between both L and R SFG area and the time it takes to fall asleep (L: t=-2.711, p=0.00681; R: t = -2.735, p=0.00633) while controlling for sex. According to these results, participants with larger SFGs would have less trouble falling asleep than those with smaller SFGs. However, when regressions covaried a measure of Whole Brain Volume (WBV), the relationship between SFG area and time to fall asleep was reduced to statistical non-significance (L: t=-1.084, p=0.279; R: t=-1.127, p=0.260). Another regression was run to determine the relationship between WBV and time to fall asleep and a statistically significant correlation was discovered (t=-2.673, p=0.00762). The analysis on hippocampal volume and bad dreams showed no significant relationship for either side (L: t=1.114, p=0.265; R: t=0.697, p=0.4860) while controlling for sex. Unsurprisingly, this relationship was also non-significant when WBV was also covaried (L: t=-0.966, p=0.334; R: t=0.464, p=0.643).</p>
</div>
<div id="conclusion" class="section level2">
<h2>Conclusion</h2>
<p>This analysis did not provide evidence for either hypothesis. For both the relationship between the SFG area and the time it takes to fall asleep and the hippocampus volume and the number of bad dreams suffered there was no meaningful statistically significant correlation. These results are a reminder that a measure of general brain size should always be included in models that involve smaller brain areas. If there had been no WBV in the model when analyzing time to fall asleep, it would have appeared that the SFG area had an effect. Instead, it was discovered that the volume of the entire brain determines how long it takes to fall asleep. These results make sense when one considers an absent control variable: age. This analysis was severely limited by the data available from basic Human Connectome Project (HCP) access, which restricts information such as race and age that could be used to identify subjects. Since the brain shrinks as one ages, and the elderly tend to have more trouble falling asleep, there should be a connection between brain size and time to fall asleep. The hippocampal analysis was also limited by available data. Only the anterior portion of the hippocampus is active in imagination, and the HCP did not segment their hippocampi into sub-areas. In addition, it is not currently known if any area of the brain is responsible for negative dreams specifically. The hippocampus, if anything, would be involved in all dreaming, good or bad, so a measure of only bad dreams would not account for all hippocampal activity. It is important to note that while increased volume or surface area in a section of brain can allow for more activity, the two are not necessarily related. Future research examining brain activity in the SFG and hippocampus during sleep problems would provide more thorough evidence for or against the hypotheses presented here.</p>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
